Controllers/AuthController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using kfubankmvc.ViewModels;
using kfubankmvc.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace kfubankmvc.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;     
 
        public AuthController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if(ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email};
                // добавляем пользователя
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    // установка куки
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }
        
        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = 
                    await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
                if (result.Succeeded)
                {
                    // проверяем, принадлежит ли URL приложению
                    if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Неправильный логин и (или) пароль");
                }
            }
            return View(model);
        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            // удаляем аутентификационные куки
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>КФУ БАНК @ViewData["Title"]</title>

    <environment include="Development">
      <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
      <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
      <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
      <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
  </head>
  <body>
  <nav style="margin-top: -50px;" class="navbar navbar-expand-lg navbar-dark bg-primary">
	  <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">КФУ БАНК</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

	  <div class="collapse navbar-collapse">
		  <ul class="navbar-nav mr-auto">
			  <li class="nav-item">
				  <a asp-area="" asp-controller="Home" asp-action="About" class="nav-link">О банке</a>
			  </li>
			  <li class="nav-item">
				  <a asp-area="" asp-controller="Home" asp-action="Contact" class="nav-link">Контакты</a>
			  </li>
		    <li class="nav-item">
			    <a asp-area="" asp-controller="Home" asp-action="Office" class="nav-link">Офисы</a>
		    </li>
		  </ul>
      @if(User.Identity.IsAuthenticated)
      {
	      <ul class="navbar-nav">
		      <li class="nav-item">
			      <a asp-area="" class="btn btn-primary mr-sm-1 " asp-controller="Account" asp-action="Index">Личный кабинет</a>
		      </li>
		      <li class="nav-item">
			      <input class="btn btn-primary mr-sm-1 " type="submit" value="Добро пожаловать, @User.Identity.Name"/>
		      </li>
              <li class="nav-item">
			      <form method="post" asp-controller="Auth" asp-action="LogOff">
				      <input class="btn btn-secondary" type="submit" value="Выход"/>
			      </form>
		      </li>
	      </ul>
          }
          else
          {
	          <ul class="navbar-nav">
		          <li class="nav-item">
			          <a asp-area="" class="btn btn-primary mr-sm-1 " asp-controller="Auth" asp-action="Register">Регистрация</a>
		          </li>
		          <li class="nav-item">
			          <a asp-area="" class="btn btn-primary mr-sm-1 " asp-controller="Auth" asp-action="Login">Вход</a>
		          </li>
            </ul>
            }
	  </div>
  </nav>
    <div class="container body-content">
      @RenderBody()
      <hr/>
      <footer>
        <p>&copy; 2018 - КФУ БАНК</p>
      </footer>
    </div>

    <environment include="Development">
      <script src="~/lib/jquery/dist/jquery.js"></script>
      <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
      <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
      <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
              asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
              asp-fallback-test="window.jQuery"
              crossorigin="anonymous"
              integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
      </script>
      <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
              asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
              asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
              crossorigin="anonymous"
              integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
      </script>
      <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
  </body>
</html>